ktor:
    environment: $KTOR_ENV
    development: true
    application:
        modules:
            - dev.timpham.ApplicationKt.module
    deployment:
        port: 8080
        watch:
            - classes

local:
    host: "http://localhost:8080"
    postgres:
        driver: "org.postgresql.Driver"
        url: "jdbc:postgresql://127.0.0.1:5432/ktor_quiz"
        user: "postgres"
        password: "admin"

    jwt:
        secret: "jwt-secret-is-very-extremely-secret"
        refreshSecret: "refresh-jwt-secret-is-very-extremely-secret"
        expireMinutes: "60"
        expireRefreshMinutes: "43200"   #    30 days
        issuer: "http://0.0.0.0:8080/"
        audience: "http://0.0.0.0:8080/hello"
        realm: "realm local"

    redis:
        host: "localhost"
        port: "6379"

dev:
    host: "http://127.0.0.1:8080"
    postgres:
        driver: "org.postgresql.Driver"
        url: "jdbc:postgresql://postgres_db:5432/ktor_quiz"
        user: "postgres"
        password: "admin"

    jwt:
        secret: "jwt-secret-is-very-extremely-secret"
        refreshSecret: "refresh-jwt-secret-is-very-extremely-secret"
        expireMinutes: "60"
        expireRefreshMinutes: "43200"   #    30 days
        issuer: "http://0.0.0.0:8080/"
        audience: "http://0.0.0.0:8080/hello"
        realm: "realm dev"

    redis:
        host: "redis"
        port: "6379"